const state = { view:'home', step:1, type:null, title:'', ksb:'', units:'', courses: JSON.parse(localStorage.getItem('naxos3_courses') || '[]') };
const $ = (s)=>document.querySelector(s);
const $$ = (s)=>[...document.querySelectorAll(s)];

function save(){localStorage.setItem('naxos3_courses',JSON.stringify(state.courses));}
function show(view){
  state.view=view;
  $$('.page,.home').forEach(x=>x.classList.add('hidden'));
  const el=$(view==='home'?'#homeView':`#${view}View`); el.classList.remove('hidden'); el.classList.add('fade-in');
  if(view==='ksb'||view==='nvq') renderLists();
  if(view==='course') renderCourse();
  if(view==='create') resetBuilder();
  window.scrollTo({top:0,behavior:'instant'});
}
function renderLists(){
  ['KSB','NVQ'].forEach(type=>{
    const key=type.toLowerCase(), list=$(`#${key}List`), empty=$(`#${key}Empty`);
    const courses=state.courses.filter(c=>c.type===type); list.innerHTML='';
    empty.classList.toggle('hidden',courses.length>0);
    courses.forEach(c=>{const b=document.createElement('button');b.className='course-card';b.innerHTML=`<span class="course-type">${c.type} course</span><h3>${esc(c.title)}</h3><p>${c.ksbCount} KSBs · ${c.unitCount} units · Draft</p>`;b.onclick=()=>{state.selected=c;show('course')};list.appendChild(b)});
  });
}
function esc(s){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));}
function parseLines(text){return text.split(/\n+/).map(x=>x.trim()).filter(Boolean)}
function resetBuilder(){
 state.step=1;state.type=null;state.title='';state.ksb='';state.units='';
 $$('.step').forEach(x=>x.classList.toggle('hidden',x.dataset.step!=='1'));$$('.progress span').forEach((x,i)=>x.classList.toggle('active',i===0));
 $('#nextStep').textContent='Continue';$('#prevStep').classList.add('hidden');
 $('#courseTitle').value='';$('#ksbInput').value='';$('#unitInput').value='';
 $$('.type-choice').forEach(x=>x.classList.remove('selected'));
}
function updateStep(){
 $$('.step').forEach(x=>x.classList.toggle('hidden',Number(x.dataset.step)!==state.step));
 $$('.progress span').forEach((x,i)=>x.classList.toggle('active',i<state.step));
 $('#prevStep').classList.toggle('hidden',state.step===1);
 $('#nextStep').textContent=state.step===3?'Build course':'Continue';
 if(state.step===3){
  const ksbs=parseLines(state.ksb),units=parseLines(state.units);
  $('#createSummary').innerHTML=`<div class="summary-row"><span>Type</span><b>${state.type} Course</b></div><div class="summary-row"><span>Course</span><b>${esc(state.title||'Untitled course')}</b></div><div class="summary-row"><span>KSB criteria</span><b>${ksbs.length}</b></div><div class="summary-row"><span>Units / activities</span><b>${units.length}</b></div>`;
 }
}
function createCourse(){
 const ksbs=parseLines(state.ksb),units=parseLines(state.units);
 const course={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),type:state.type,title:state.title||'Untitled course',ksbs,units,ksbCount:ksbs.length,unitCount:units.length,created:new Date().toISOString(),status:'Draft'};
 state.courses.unshift(course);save();state.selected=course;show('course');
}
function renderCourse(){
 const c=state.selected;if(!c)return;
 $('#courseArea').textContent=`${c.type} Course`;
 $('#courseHeading').textContent=c.title;
 $('#courseOverview').innerHTML=`<div class="overview-hero"><span class="course-type">Generated by Naxos</span><h2>${esc(c.title)}</h2><p>First-pass course structure ready to edit. Naxos will become the course-generation engine for KSB mapping and evidence design.</p></div><div class="stat-grid"><div class="stat"><b>${c.ksbCount}</b><span>KSB criteria</span></div><div class="stat"><b>${c.unitCount}</b><span>Units / activities</span></div><div class="stat"><b>Draft</b><span>Status</span></div></div><div class="section-card"><h3>Course content</h3>${c.units.length?c.units.map(x=>`<span class="pill">${esc(x)}</span>`).join(''):'<p class="muted">No unit titles supplied yet.</p>'}</div><div class="section-card"><h3>KSBs</h3>${c.ksbs.length?c.ksbs.map(x=>`<span class="pill">${esc(x)}</span>`).join(''):'<p class="muted">No KSBs supplied yet.</p>'}</div>`;
}

$('#naxosOrb').addEventListener('click',()=>{const w=$('.orb-wrap'),open=w.classList.toggle('open');$('#naxosOrb').setAttribute('aria-expanded',open);$('#mainMenu').setAttribute('aria-hidden',!open)});
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>show(b.dataset.view)));
$$('[data-home]').forEach(b=>b.addEventListener('click',()=>show('home')));
$$('.type-choice').forEach(b=>b.addEventListener('click',()=>{$$('.type-choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');state.type=b.dataset.type;state.step=2;updateStep()}));
$('#nextStep').addEventListener('click',()=>{
 if(state.step===2){state.title=$('#courseTitle').value.trim();state.ksb=$('#ksbInput').value;state.units=$('#unitInput').value;if(!state.type)return;state.step=3;updateStep();return}
 if(state.step===3){createCourse();return}
 if(state.step===1 && state.type)state.step=2;updateStep();
});
$('#prevStep').addEventListener('click',()=>{if(state.step>1){state.step--;updateStep()}});
$('#editCourse').addEventListener('click',()=>{if(!state.selected)return;state.type=state.selected.type;state.title=state.selected.title;state.ksb=state.selected.ksbs.join('\n');state.units=state.selected.units.join('\n');show('create');state.step=2;$('#courseTitle').value=state.title;$('#ksbInput').value=state.ksb;$('#unitInput').value=state.units;updateStep()});
show('home');
