const state={view:'home',selected:null,courses:JSON.parse(localStorage.getItem('naxos3_courses')||'[]'),draft:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const save=()=>localStorage.setItem('naxos3_courses',JSON.stringify(state.courses));
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function blankDraft(){return{type:'KSB',title:'',ref:'',version:'',level:'',duration:'',ksbs:[],units:[]}}
function parseKSB(text){return String(text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{const m=line.match(/^([KSB])\s*([0-9]+)\s*[:\-–—]?\s*(.*)$/i);return m?{reference:m[1].toUpperCase()+m[2],ksb_type:m[1].toUpperCase(),description:m[3].trim()}:null}).filter(Boolean)}
function show(view){state.view=view;$$('.page,.home').forEach(x=>x.classList.add('hidden'));const el=$(view==='home'?'#homeView':`#${view}View`);if(el)el.classList.remove('hidden');if(view==='ksb'||view==='nvq')renderLists();if(view==='course')renderCourse();if(view==='create')startCreate();window.scrollTo({top:0,behavior:'instant'})}
function renderLists(){['KSB','NVQ'].forEach(type=>{const key=type.toLowerCase(),list=$(`#${key}List`),empty=$(`#${key}Empty`),items=state.courses.filter(c=>c.type===type);list.innerHTML='';empty.classList.toggle('hidden',items.length>0);items.forEach(c=>{const b=document.createElement('button');b.className='course-card';b.innerHTML=`<span class="course-type">${esc(c.type)} course</span><h3>${esc(c.title)}</h3><p>${c.ksbs?.length||0} KSBs · ${c.units?.length||0} units · ${(c.units||[]).reduce((n,u)=>n+(u.activities?.length||0),0)} activities</p>`;b.onclick=()=>{state.selected=c;show('course')};list.appendChild(b)})})}
function startCreate(){state.draft=blankDraft();renderBuilder()}
function typeButtons(){ $$('.type-choice').forEach(b=>b.onclick=()=>{state.draft.type=b.dataset.type;$$('.type-choice').forEach(x=>x.classList.toggle('selected',x===b))}) }
function renderBuilder(){const d=state.draft;if(!d)return;$('#builder').innerHTML=`
<div class="designer-head"><div><span class="step-kicker">Manual course designer</span><h2>Build your course</h2><p class="muted">Everything is created by you. Nothing is automatically mapped.</p></div><div class="designer-save"><span>${d.units.length} units</span><span>${d.ksbs.length} KSBs</span></div></div>
<div class="designer-section"><div class="section-heading"><div><span class="section-number">01</span><div><h3>Course details</h3><p>Enter the information exactly as you want it stored.</p></div></div></div><div class="type-grid"><button class="type-choice ${d.type==='KSB'?'selected':''}" data-type="KSB"><b>KSB Course</b><span>Standards-led course with KSB mapping.</span></button><button class="type-choice ${d.type==='NVQ'?'selected':''}" data-type="NVQ"><b>NVQ Course</b><span>Practical vocational course structure.</span></button></div><div class="form-grid"><label>Course title<input id="dTitle" value="${esc(d.title)}" placeholder="e.g. Bricklayer"></label><label>Standard / reference<input id="dRef" value="${esc(d.ref)}" placeholder="e.g. ST0095"></label><label>Version<input id="dVersion" value="${esc(d.version)}" placeholder="e.g. 1.2"></label><label>Level<input id="dLevel" value="${esc(d.level)}" placeholder="e.g. 2"></label><label>Duration<input id="dDuration" value="${esc(d.duration)}" placeholder="e.g. 24 months"></label></div></div>
<div class="designer-section"><div class="section-heading"><div><span class="section-number">02</span><div><h3>KSB library</h3><p>Add every K, S and B manually. Full descriptions stay visible when mapping.</p></div></div><button class="small-action" id="addKsb">+ Add KSB</button></div><div class="ksb-add-row"><input id="newRef" placeholder="K1 / S1 / B1"><textarea id="newDesc" rows="2" placeholder="Full KSB description"></textarea><button class="secondary" id="addOneKsb">Add</button></div><div class="paste-row"><textarea id="pasteKsb" rows="4" placeholder="Or paste multiple criteria, one per line:\nK1: full description\nS1: full description\nB1: full description"></textarea><button class="secondary" id="importKsb">Add all criteria</button></div><div id="ksbLibrary" class="ksb-library"></div></div>
<div class="designer-section"><div class="section-heading"><div><span class="section-number">03</span><div><h3>Units</h3><p>Create units yourself, then tick the KSBs covered by each unit.</p></div></div><button class="small-action" id="addUnit">+ Add unit</button></div><div id="unitBuilder"></div></div>
<div class="designer-footer"><button class="secondary" id="cancelBuild">Cancel</button><button class="next" id="saveCourse">Save course</button></div>`;
 typeButtons();
 ['dTitle','dRef','dVersion','dLevel','dDuration'].forEach(id=>$('#'+id).addEventListener('input',e=>{d[{dTitle:'title',dRef:'ref',dVersion:'version',dLevel:'level',dDuration:'duration'}[id]]=e.target.value}));
 $('#addKsb').onclick=()=>$('#newRef').focus();$('#addOneKsb').onclick=addOneKsb;$('#importKsb').onclick=importKsb;$('#addUnit').onclick=()=>{d.units.push({id:uid(),title:'New unit',description:'',ksb_ids:[],activities:[]});renderBuilder();setTimeout(()=>document.querySelector('#unitBuilder .unit:last-child')?.scrollIntoView({behavior:'smooth',block:'center'}),50)};$('#cancelBuild').onclick=()=>show('home');$('#saveCourse').onclick=saveCourse;renderKsbLibrary();renderUnits()}
function addOneKsb(){const ref=$('#newRef').value.trim().toUpperCase().replace(/\s+/g,'');const desc=$('#newDesc').value.trim();if(!/^[KSB]\d+$/.test(ref)||!desc){alert('Enter a K, S or B reference and its full description.');return}if(state.draft.ksbs.some(x=>x.reference===ref)){alert(`${ref} already exists.`);return}state.draft.ksbs.push({id:uid(),reference:ref,ksb_type:ref[0],description:desc});$('#newRef').value='';$('#newDesc').value='';renderKsbLibrary();renderUnits()}
function importKsb(){const rows=parseKSB($('#pasteKsb').value);if(!rows.length){alert('No KSB criteria were recognised. Use K1:, S1: or B1: at the start of each line.');return}rows.forEach(x=>{if(!state.draft.ksbs.some(k=>k.reference===x.reference))state.draft.ksbs.push({id:uid(),...x})});$('#pasteKsb').value='';renderKsbLibrary();renderUnits()}
function removeKsb(id){state.draft.ksbs=state.draft.ksbs.filter(x=>x.id!==id);state.draft.units.forEach(u=>{u.ksb_ids=u.ksb_ids.filter(x=>x!==id);u.activities.forEach(a=>a.ksb_ids=a.ksb_ids.filter(x=>x!==id))});renderBuilder()}
function coverageCount(id,excludeActivityId=null){let n=0;state.draft.units.forEach(u=>u.activities.forEach(a=>{if(a.id!==excludeActivityId)n+=(a.ksb_ids||[]).filter(x=>x===id).length}));return n}
function ksbLabel(k,count){return `<div class="ksb-ref ${k.ksb_type}">${esc(k.reference)}</div><div class="ksb-copy"><strong>${esc(k.description)}</strong><span>${count} ${count===1?'activity':'activities'} cover this KSB</span></div>`}
function renderKsbLibrary(){const box=$('#ksbLibrary');if(!box)return;const d=state.draft;if(!d.ksbs.length){box.innerHTML='<div class="empty-mini">No KSBs added yet.</div>';return}box.innerHTML=d.ksbs.map(k=>`<div class="ksb-row">${ksbLabel(k,coverageCount(k.id))}<button class="remove-k" data-id="${k.id}" aria-label="Remove ${k.reference}">×</button></div>`).join('');$$('.remove-k').forEach(b=>b.onclick=()=>removeKsb(b.dataset.id))}
function renderUnits(){const box=$('#unitBuilder');if(!box)return;const d=state.draft;if(!d.units.length){box.innerHTML='<div class="empty-mini unit-empty">No units yet. Select + Add unit to start building the course.</div>';return}box.innerHTML=d.units.map((u,i)=>`<article class="unit" data-id="${u.id}"><div class="unit-top"><div class="unit-index">${String(i+1).padStart(2,'0')}</div><div class="unit-fields"><input class="unit-title" value="${esc(u.title)}" placeholder="Unit title"><textarea class="unit-desc" rows="2" placeholder="Unit description">${esc(u.description)}</textarea></div><button class="remove-unit" data-id="${u.id}">Remove</button></div><div class="mapping-panel"><div class="mapping-title"><div><b>Unit KSBs</b><span>Tick every K, S or B this unit covers.</span></div><span>${u.ksb_ids.length} selected</span></div><div class="picker-grid">${d.ksbs.map(k=>`<label class="ksb-picker ${u.ksb_ids.includes(k.id)?'checked':''}"><input type="checkbox" data-unit="${u.id}" data-ksb="${k.id}" ${u.ksb_ids.includes(k.id)?'checked':''}><span class="checkmark">✓</span>${ksbLabel(k,coverageCount(k.id))}</label>`).join('')}</div></div><div class="activity-head"><div><b>Activities</b><span>${u.activities.length} added</span></div><button class="small-action add-activity" data-unit="${u.id}">+ Add activity</button></div><div class="activity-list">${u.activities.map((a,j)=>activityCard(u,a,j)).join('')}</div></article>`).join('');
 $$('.unit-title').forEach(el=>el.oninput=()=>{const u=d.units.find(x=>x.id===el.closest('.unit').dataset.id);u.title=el.value});$$('.unit-desc').forEach(el=>el.oninput=()=>{const u=d.units.find(x=>x.id===el.closest('.unit').dataset.id);u.description=el.value});
 $$('.remove-unit').forEach(b=>b.onclick=()=>{d.units=d.units.filter(u=>u.id!==b.dataset.id);renderBuilder()});$$('.ksb-picker input').forEach(ch=>ch.onchange=()=>{const u=d.units.find(x=>x.id===ch.dataset.unit);ch.checked?u.ksb_ids.push(ch.dataset.ksb):u.ksb_ids=u.ksb_ids.filter(id=>id!==ch.dataset.ksb);ch.closest('.ksb-picker').classList.toggle('checked',ch.checked);ch.closest('.mapping-panel').querySelector('.mapping-title>span').textContent=`${u.ksb_ids.length} selected`;});$$('.add-activity').forEach(b=>b.onclick=()=>{const u=d.units.find(x=>x.id===b.dataset.unit);u.activities.push({id:uid(),title:'New activity',type:'practical_evidence',photo_instruction:'',written_prompt:'',photo_required:true,written_required:true,ksb_ids:[]});renderUnits();setTimeout(()=>document.querySelector(`[data-id="${u.id}"] .activity:last-child`)?.scrollIntoView({behavior:'smooth',block:'center'}),50)});bindActivityEvents()}
function activityCard(u,a,j){const types=[['practical_evidence','Practical evidence'],['knowledge_question','Knowledge'],['witness_testimony','Witness testimony'],['other','Other']];return `<div class="activity" data-id="${a.id}"><div class="activity-top"><span class="activity-number">${j+1}</span><div class="activity-title-wrap"><input class="activity-title" value="${esc(a.title)}" placeholder="Activity title"><select class="activity-type">${types.map(t=>`<option value="${t[0]}" ${a.type===t[0]?'selected':''}>${t[1]}</option>`).join('')}</select></div><button class="remove-activity">×</button></div><div class="activity-fields"><label>Photo instruction<textarea class="photo-instruction" rows="2" placeholder="What should the learner photograph?">${esc(a.photo_instruction)}</textarea></label><label>Written response prompt<textarea class="written-prompt" rows="3" placeholder="What should the learner explain?">${esc(a.written_prompt)}</textarea></label></div><div class="activity-options"><label><input class="photo-required" type="checkbox" ${a.photo_required?'checked':''}> Photo required</label><label><input class="written-required" type="checkbox" ${a.written_required?'checked':''}> Written response required</label></div><div class="mapping-panel activity-mapping"><div class="mapping-title"><div><b>Activity KSBs</b><span>Tick any KSBs covered by this activity. They can be selected again in other activities.</span></div><span>${a.ksb_ids.length} selected</span></div><div class="picker-grid activity-picker">${state.draft.ksbs.map(k=>{const count=coverageCount(k.id,a.id);return `<label class="ksb-picker ${a.ksb_ids.includes(k.id)?'checked':''}"><input type="checkbox" data-activity="${a.id}" data-unit="${u.id}" data-ksb="${k.id}" ${a.ksb_ids.includes(k.id)?'checked':''}><span class="checkmark">✓</span><span class="coverage-number">${count}×</span>${ksbLabel(k,count)}</label>`}).join('')}</div></div></div>`}
function bindActivityEvents(){const d=state.draft;$$('.activity').forEach(el=>{const a=d.units.flatMap(u=>u.activities).find(x=>x.id===el.dataset.id),u=d.units.find(x=>x.activities.some(x=>x.id===a.id));el.querySelector('.activity-title').oninput=e=>a.title=e.target.value;el.querySelector('.activity-type').onchange=e=>a.type=e.target.value;el.querySelector('.photo-instruction').oninput=e=>a.photo_instruction=e.target.value;el.querySelector('.written-prompt').oninput=e=>a.written_prompt=e.target.value;el.querySelector('.photo-required').onchange=e=>a.photo_required=e.target.checked;el.querySelector('.written-required').onchange=e=>a.written_required=e.target.checked;el.querySelector('.remove-activity').onclick=()=>{u.activities=u.activities.filter(x=>x.id!==a.id);renderUnits();renderKsbLibrary()}});$$('.activity-picker input').forEach(ch=>ch.onchange=()=>{const u=d.units.find(x=>x.id===ch.dataset.unit),a=u.activities.find(x=>x.id===ch.dataset.activity);ch.checked?a.ksb_ids.push(ch.dataset.ksb):a.ksb_ids=a.ksb_ids.filter(id=>id!==ch.dataset.ksb);renderUnits();renderKsbLibrary()})}
function saveCourse(){const d=state.draft;if(!d.type||!d.title.trim()){alert('Choose KSB/NVQ and enter a course title.');return}if(!d.ksbs.length){alert('Add at least one KSB.');return}if(!d.units.length){alert('Add at least one unit.');return}const course={id:uid(),type:d.type,title:d.title.trim(),reference:d.ref.trim(),version:d.version.trim(),level:d.level.trim(),duration:d.duration.trim(),ksbs:d.ksbs.map(k=>({...k})),units:d.units.map(u=>({...u,ksb_ids:[...u.ksb_ids],activities:u.activities.map(a=>({...a,ksb_ids:[...a.ksb_ids]}))}))};course.ksbCount=course.ksbs.length;course.packCount=course.units.length;course.activityCount=course.units.reduce((n,u)=>n+u.activities.length,0);state.courses.push(course);save();state.selected=course;show('course')}
function renderCourse(){const c=state.selected;if(!c)return;$('#courseArea').textContent=`${c.type} Course`;$('#courseHeading').textContent=c.title;$('#courseOverview').innerHTML=`<div class="overview-hero"><span class="eyebrow">${esc(c.reference||'Course')}</span><h2>${esc(c.title)}</h2><p>${esc(c.version?`Version ${c.version} · `:'')}${esc(c.level?`Level ${c.level} · `:'')}${esc(c.duration||'')}</p></div><div class="stat-grid"><div class="stat"><b>${c.ksbs?.length||0}</b><span>KSB criteria</span></div><div class="stat"><b>${c.units?.length||0}</b><span>Units</span></div><div class="stat"><b>${(c.units||[]).reduce((n,u)=>n+(u.activities?.length||0),0)}</b><span>Activities</span></div></div><div class="section-card"><h3>Units</h3>${(c.units||[]).map((u,i)=>`<div class="saved-unit"><b>${i+1}. ${esc(u.title)}</b><span>${u.ksb_ids.length} KSBs · ${u.activities.length} activities</span></div>`).join('')}</div><div class="section-card"><h3>KSB coverage</h3><div class="saved-ksbs">${(c.ksbs||[]).map(k=>`<span class="pill">${esc(k.reference)} · ${coverageForCourse(c,k.id)}×</span>`).join('')}</div></div>`}
function coverageForCourse(c,id){return (c.units||[]).reduce((n,u)=>n+(u.activities||[]).reduce((m,a)=>m+(a.ksb_ids||[]).filter(x=>x===id).length,0),0)}
$('#editCourse')?.addEventListener('click',()=>{if(state.selected){state.draft={type:state.selected.type,title:state.selected.title,ref:state.selected.reference,version:state.selected.version,level:state.selected.level,duration:state.selected.duration,ksbs:state.selected.ksbs.map(k=>({...k})),units:state.selected.units.map(u=>({...u,ksb_ids:[...u.ksb_ids],activities:u.activities.map(a=>({...a,ksb_ids:[...a.ksb_ids]}))}))};show('create')}});
$('#naxosOrb')?.addEventListener('click',()=>{$('#naxosOrb').parentElement.classList.toggle('open');$('#naxosOrb').setAttribute('aria-expanded',$('#naxosOrb').parentElement.classList.contains('open'))});
document.addEventListener('click',e=>{const view=e.target.closest('[data-view]')?.dataset.view;if(view){$('#naxosOrb')?.parentElement.classList.remove('open');show(view)}if(e.target.closest('[data-home]'))show('home')});
