(()=>{
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
const blank=()=>({id:null,type:'KSB',title:'',ref:'',version:'',level:'',duration:'',website:'',duties:[],ksbs:[],sections:[],status:'draft'});
const parse=text=>String(text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{const m=line.match(/^([KSB])\s*(\d+)\s*[:\-–—]?\s*(.*)$/i);return m?{id:uid(),reference:m[1].toUpperCase()+m[2],ksb_type:m[1].toUpperCase(),description:m[3].trim()}:null}).filter(Boolean);
function newSection(type,title){return{id:uid(),type,title,description:'',units:[]}}
function activity(title,type,ksbs=[]){return{id:uid(),title,type,photo_instruction:'',written_prompt:'',reflection_prompt:'',ksb_ids:[...ksbs],photo_required:type==='practical',written_required:type!=='witness',reflection_required:type==='witness'}}
function unit(title,category,ksbs=[]){return{id:uid(),title,description:'',category,ksb_ids:[...ksbs],activities:[]}}
function sectionDefaults(d){const by=t=>d.ksbs.filter(k=>k.ksb_type===t);const sections=[newSection('trade','Trade Skills'),newSection('supporting','Supporting'),newSection('main','Main'),newSection('knowledge','Knowledge'),newSection('behaviours','Behaviours')];
 by('S').forEach(k=>sections[1].units.push(unit(k.reference+' — '+k.description,'supporting',[k.id])));
 by('K').forEach(k=>sections[3].units.push(unit(k.reference+' — '+k.description,'knowledge',[k.id])));
 by('B').forEach(k=>sections[4].units.push(unit(k.reference+' — '+k.description,'behaviours',[k.id])));
 return sections;
}
function coverage(d,id){let n=0;(d.sections||[]).forEach(s=>(s.units||[]).forEach(u=>{n+=(u.ksb_ids||[]).filter(x=>x===id).length;(u.activities||[]).forEach(a=>n+=(a.ksb_ids||[]).filter(x=>x===id).length)}));return n}
function picker(d,selected){return `<div class="studio-picker">${d.ksbs.map(k=>`<label class="studio-pick ${selected.includes(k.id)?'selected':''}"><input type="checkbox" data-ksb="${k.id}" ${selected.includes(k.id)?'checked':''}><b class="ksb-ref ${k.ksb_type}">${esc(k.reference)}</b><span>${esc(k.description)}</span><small>${coverage(d,k.id)}×</small></label>`).join('')}</div>`}
function renderBuilder(){const d=state.draft;if(!d)return;$('#builder').innerHTML=`<div class="studio-head"><div><span class="step-kicker">Naxos 3.0 Course Builder</span><h2>Build the master course</h2><p class="muted">Enter the course once, then build its Naxos structure. The master KSB library remains separate from the evidence structure.</p></div><div class="studio-stat"><b>${d.ksbs.length}</b><span>KSBs</span><b>${d.sections.length}</b><span>Sections</span></div></div>
<section class="studio-section"><div class="studio-section-title"><span>01</span><div><h3>Course information</h3><p>These details belong to the master course.</p></div></div><div class="type-grid"><button class="type-choice ${d.type==='KSB'?'selected':''}" data-type="KSB"><b>KSB Course</b><span>Standards-led course.</span></button><button class="type-choice ${d.type==='NVQ'?'selected':''}" data-type="NVQ"><b>NVQ Course</b><span>Practical vocational course.</span></button></div><div class="form-grid"><label>Course title<input id="sbTitle" value="${esc(d.title)}" placeholder="e.g. Bricklayer"></label><label>Standard / reference<input id="sbRef" value="${esc(d.ref)}"></label><label>Version<input id="sbVersion" value="${esc(d.version)}"></label><label>Level<input id="sbLevel" value="${esc(d.level)}"></label><label>Duration<input id="sbDuration" value="${esc(d.duration)}"></label><label>Official standard website<input id="sbWebsite" value="${esc(d.website)}" placeholder="https://..."></label></div></section>
<section class="studio-section"><div class="studio-section-title"><span>02</span><div><h3>Duties</h3><p>Optional. Paste one duty per line.</p></div></div><textarea id="sbDuties" rows="4" placeholder="D1: Prepare for work\nD2: Carry out occupational tasks">${esc(d.duties.map(x=>`${x.reference}: ${x.title}`).join('\n'))}</textarea></section>
<section class="studio-section"><div class="studio-section-title"><span>03</span><div><h3>Complete KSB library</h3><p>Paste the complete KSB list once. Naxos keeps the official descriptions in the master course.</p></div></div><textarea id="sbKsb" rows="10" placeholder="K1: Knowledge description\nS1: Skill description\nB1: Behaviour description">${esc(d.ksbs.map(k=>`${k.reference}: ${k.description}`).join('\n'))}</textarea><div class="studio-actions"><button class="secondary" id="sbReplace">Replace KSBs</button><button class="secondary" id="sbAppend">Add KSBs</button></div><div class="studio-summary"><span><b>${d.ksbs.filter(k=>k.ksb_type==='K').length}</b> Knowledge</span><span><b>${d.ksbs.filter(k=>k.ksb_type==='S').length}</b> Skills</span><span><b>${d.ksbs.filter(k=>k.ksb_type==='B').length}</b> Behaviours</span><span><b>${d.ksbs.length}</b> Total</span></div></section>
<section class="studio-section"><div class="studio-section-title"><span>04</span><div><h3>Naxos structure</h3><p>The standard Naxos structure is always five sections: Trade Skills, Supporting, Main, Knowledge and Behaviours.</p></div></div><div class="naxos-architecture"><div><b>Trade Skills</b><span>General and cross-cutting occupational requirements.</span></div><div><b>Supporting</b><span>Supporting technical Skills with their associated Knowledge.</span></div><div><b>Main</b><span>Core occupational competency and major practical Skills.</span></div><div><b>Knowledge</b><span>Only Knowledge with no genuine Skill match.</span></div><div><b>Behaviours</b><span>Witness testimony and learner reflection.</span></div></div><button class="studio-generate" id="sbGenerate">Generate five-section structure</button><div id="sectionEditor">${sectionsHtml(d)}</div></section>
<div class="designer-footer"><button class="secondary" id="sbCancel">Cancel</button><button class="next" id="sbSave">Save completed course</button></div>`;
 const map={sbTitle:'title',sbRef:'ref',sbVersion:'version',sbLevel:'level',sbDuration:'duration',sbWebsite:'website'};Object.entries(map).forEach(([id,k])=>$('#'+id).oninput=e=>d[k]=e.target.value);
 $$('.type-choice').forEach(b=>b.onclick=()=>{d.type=b.dataset.type;renderBuilder()});
 $('#sbDuties').onchange=e=>{d.duties=String(e.target.value).split(/\n+/).map((x,i)=>{x=x.trim();if(!x)return null;const m=x.match(/^(?:D(?:uty)?\s*)?(\d+)\s*[:\-–—.]?\s*(.*)$/i);return{id:uid(),reference:m?'D'+m[1]:'D'+(i+1),title:m?m[2]:x}}).filter(Boolean);};
 $('#sbReplace').onclick=()=>{const r=parse($('#sbKsb').value);if(!r.length)return alert('No KSBs recognised.');d.ksbs=r;renderBuilder()};
 $('#sbAppend').onclick=()=>{parse($('#sbKsb').value).forEach(k=>{if(!d.ksbs.some(x=>x.reference===k.reference))d.ksbs.push(k)});renderBuilder()};
 $('#sbGenerate').onclick=()=>{d.sections=sectionDefaults(d);renderBuilder()};
 bindSections();$('#sbCancel').onclick=()=>show('home');$('#sbSave').onclick=saveBuiltCourse;
}
function sectionsHtml(d){return (d.sections||[]).map((s,si)=>`<article class="naxos-section" data-section="${s.id}"><header><span>${String(si+1).padStart(2,'0')}</span><div><input class="section-title" value="${esc(s.title)}"><small>${esc(s.type)}</small></div><button class="small-action add-unit" data-section="${s.id}">+ Unit</button></header><p class="muted">${sectionHint(s.type)}</p><div class="section-units">${(s.units||[]).map((u,ui)=>unitHtml(d,s,u,ui)).join('')}</div></article>`).join('')||'<div class="empty-mini">Generate the five-section structure to begin.</div>'}
function sectionHint(t){return({trade:'General/cross-cutting trade requirements. Evidence is mainly written, audio or reflection unless practical evidence is useful.',supporting:'Supporting Skills are separate units. Their associated Knowledge stays with the Skill where there is a genuine occupational connection.',main:'Core occupational competency. Use photos, video, audio, write-ups and reflections as appropriate.',knowledge:'Only unmatched Knowledge criteria should live here.',behaviours:'Behaviour evidence is normally witness testimony plus learner reflection.'}[t]||'')}
function unitHtml(d,s,u,ui){return `<div class="naxos-unit" data-unit="${u.id}"><div class="unit-top"><div class="unit-index">${String(ui+1).padStart(2,'0')}</div><div class="unit-fields"><input class="unit-title" value="${esc(u.title)}"><textarea class="unit-desc" rows="2" placeholder="Unit description">${esc(u.description)}</textarea></div><button class="remove-unit" data-unit="${u.id}" data-section="${s.id}">Remove</button></div><div class="mapping-title"><b>Unit KSB ownership</b><span>${u.ksb_ids.length} selected</span></div>${picker(d,u.ksb_ids)}<div class="activity-head"><div><b>Evidence activities</b><span>${u.activities.length} added</span></div><button class="small-action add-activity" data-unit="${u.id}" data-section="${s.id}">+ Activity</button></div><div class="activity-list">${u.activities.map((a,ai)=>activityHtml(d,s,u,a,ai)).join('')}</div></div>`}
function activityHtml(d,s,u,a,i){const types=[['practical','Practical evidence'],['knowledge','Knowledge response'],['witness','Witness testimony'],['reflection','Learner reflection'],['other','Other']];return `<div class="studio-activity" data-activity="${a.id}"><div class="activity-top"><span>${i+1}</span><input class="activity-title" value="${esc(a.title)}"><select class="activity-type">${types.map(t=>`<option value="${t[0]}" ${a.type===t[0]?'selected':''}>${t[1]}</option>`).join('')}</select><button class="remove-activity">×</button></div><div class="activity-fields"><label>Photo / practical instruction<textarea class="photo-instruction" rows="2">${esc(a.photo_instruction)}</textarea></label><label>Written response prompt<textarea class="written-prompt" rows="2">${esc(a.written_prompt)}</textarea></label><label>Reflection / witness prompt<textarea class="reflection-prompt" rows="2">${esc(a.reflection_prompt)}</textarea></label></div><div class="activity-options"><label><input class="photo-required" type="checkbox" ${a.photo_required?'checked':''}> Photo required</label><label><input class="written-required" type="checkbox" ${a.written_required?'checked':''}> Written response required</label><label><input class="reflection-required" type="checkbox" ${a.reflection_required?'checked':''}> Reflection required</label></div><div class="mapping-title"><b>Activity KSBs</b><span>${a.ksb_ids.length} selected</span></div>${picker(d,a.ksb_ids)}</div>`}
function bindSections(){const d=state.draft;$$('.section-title').forEach(e=>e.oninput=()=>{const s=d.sections.find(x=>x.id===e.closest('.naxos-section').dataset.section);s.title=e.value});$$('.unit-title').forEach(e=>e.oninput=()=>{const u=d.sections.flatMap(s=>s.units).find(x=>x.id===e.closest('.naxos-unit').dataset.unit);u.title=e.value});$$('.unit-desc').forEach(e=>e.oninput=()=>{const u=d.sections.flatMap(s=>s.units).find(x=>x.id===e.closest('.naxos-unit').dataset.unit);u.description=e.value});
 $$('.remove-unit').forEach(b=>b.onclick=()=>{const s=d.sections.find(x=>x.id===b.dataset.section);s.units=s.units.filter(u=>u.id!==b.dataset.unit);renderBuilder()});$$('.add-unit').forEach(b=>b.onclick=()=>{const s=d.sections.find(x=>x.id===b.dataset.section);s.units.push(unit('New unit',s.type));renderBuilder()});
 $$('.studio-pick input').forEach(ch=>ch.onchange=()=>{const host=ch.closest('.naxos-unit,.studio-activity');const id=host.dataset.unit||host.dataset.activity;let target=null;if(host.classList.contains('naxos-unit'))target=d.sections.flatMap(s=>s.units).find(u=>u.id===id);else target=d.sections.flatMap(s=>s.units).flatMap(u=>u.activities).find(a=>a.id===id);if(ch.checked&&!target.ksb_ids.includes(ch.dataset.ksb))target.ksb_ids.push(ch.dataset.ksb);if(!ch.checked)target.ksb_ids=target.ksb_ids.filter(x=>x!==ch.dataset.ksb);ch.closest('.studio-pick').classList.toggle('selected',ch.checked);});
 $$('.add-activity').forEach(b=>b.onclick=()=>{const u=d.sections.find(s=>s.id===b.dataset.section).units.find(x=>x.id===b.dataset.unit);u.activities.push(activity('New evidence activity','practical'));renderBuilder()});$$('.studio-activity').forEach(el=>{const a=d.sections.flatMap(s=>s.units).flatMap(u=>u.activities).find(x=>x.id===el.dataset.activity);el.querySelector('.activity-title').oninput=e=>a.title=e.target.value;el.querySelector('.activity-type').onchange=e=>{a.type=e.target.value;a.photo_required=e.target.value==='practical';a.written_required=e.target.value==='knowledge';a.reflection_required=e.target.value==='witness'||e.target.value==='reflection'};el.querySelector('.photo-instruction').oninput=e=>a.photo_instruction=e.target.value;el.querySelector('.written-prompt').oninput=e=>a.written_prompt=e.target.value;el.querySelector('.reflection-prompt').oninput=e=>a.reflection_prompt=e.target.value;el.querySelector('.photo-required').onchange=e=>a.photo_required=e.target.checked;el.querySelector('.written-required').onchange=e=>a.written_required=e.target.checked;el.querySelector('.reflection-required').onchange=e=>a.reflection_required=e.target.checked;el.querySelector('.remove-activity').onclick=()=>{d.sections.forEach(s=>s.units.forEach(u=>u.activities=u.activities.filter(x=>x.id!==a.id)));renderBuilder()}})}
function saveBuiltCourse(){const d=state.draft;if(!d.title.trim()||!d.ksbs.length){alert('Enter a course title and add the complete KSB library.');return}if(!d.sections.length){alert('Generate the five-section structure first.');return}const course=JSON.parse(JSON.stringify(d));course.id=course.id||uid();course.status='completed';course.masterCourse=true;course.ksbCount=course.ksbs.length;course.unitCount=course.sections.reduce((n,s)=>n+s.units.length,0);course.activityCount=course.sections.reduce((n,s)=>n+s.units.reduce((m,u)=>m+u.activities.length,0),0);const idx=state.courses.findIndex(x=>x.id===course.id);if(idx>=0)state.courses[idx]=course;else state.courses.push(course);save();state.selected=course;show('course')}
function renderCourse(){const c=state.selected;if(!c)return;$('#courseArea').textContent=(c.type||'KSB')+' Course';$('#courseHeading').textContent=c.title;const k=c.ksbs||[];$('#courseOverview').innerHTML=`<div class="course-overview-card"><div class="course-status">${c.status==='completed'?'Completed course':'Draft course'}</div><h2>${esc(c.title)}</h2><p>${esc(c.ref||'')} ${esc(c.version||'')} ${c.level?'· Level '+esc(c.level):''} ${esc(c.duration||'')}</p><div class="course-stat-row"><span><b>${k.length}</b>KSBs</span><span><b>${c.sections?.length||0}</b>Sections</span><span><b>${c.unitCount||0}</b>Units</span><span><b>${c.activityCount||0}</b>Activities</span></div>${(c.sections||[]).map(s=>`<section class="course-section-view"><h3>${esc(s.title)}</h3><p>${esc(sectionHint(s.type))}</p>${s.units.map(u=>`<article><h4>${esc(u.title)}</h4><p>${esc(u.description||'')}</p><div class="course-kchips">${u.ksb_ids.map(id=>k.find(x=>x.id===id)).filter(Boolean).map(x=>`<span>${esc(x.reference)}</span>`).join('')}</div><div class="course-activities">${u.activities.map(a=>`<div><b>${esc(a.title)}</b><small>${esc(a.type)}</small></div>`).join('')}</div></article>`).join('')}</section>`).join('')}<div class="course-actions"><button class="secondary" id="editCurrent">Edit course</button><button class="danger" id="deleteCurrent">Delete course</button></div></div>`;$('#editCurrent').onclick=()=>{state.draft=JSON.parse(JSON.stringify(c));renderBuilder();show('create')};$('#deleteCurrent').onclick=()=>{if(confirm(`Delete “${c.title}”?`)){state.courses=state.courses.filter(x=>x.id!==c.id);save();state.selected=null;show(c.type==='NVQ'?'nvq':'ksb')}}}
window.startCreate=()=>{state.draft=blank();renderBuilder()};window.renderBuilder=renderBuilder;window.renderCourse=renderCourse;
})();