(()=>{
const studioTemplates=[
 {id:'5x5x5',name:'5 × 5 × 5',desc:'Five units, five activities per unit, balanced KSB coverage.',kind:'balanced'},
 {id:'units',name:'Units',desc:'Organise the course into logical learning and evidence units.',kind:'units'},
 {id:'duty-led',name:'Duty-led',desc:'Build around the occupational duties, with KSBs mapped beneath them.',kind:'duties'},
 {id:'skill-led',name:'Skill-led',desc:'Create a main activity for each Skill and attach relevant Knowledge and Behaviours.',kind:'skills'},
 {id:'knowledge-led',name:'Knowledge-led',desc:'Build learning around Knowledge criteria while linking practical Skills and Behaviours.',kind:'knowledge'},
 {id:'individual-ksb',name:'Individual KSB',desc:'Give each KSB its own activity.',kind:'individual'},
 {id:'holistic',name:'Holistic',desc:'Use fewer activities with deliberate multi-KSB coverage.',kind:'holistic'},
 {id:'evidence-packs',name:'Evidence Packs',desc:'Group practical evidence into complete workplace evidence packs.',kind:'evidence'},
 {id:'photo-dump',name:'Photo Dump',desc:'Collect workplace evidence first and organise it afterwards.',kind:'photo'},
 {id:'ai-sorting',name:'AI Sorting',desc:'Start with evidence and let AI suggest duties, activities and KSB mappings.',kind:'ai'},
 {id:'epa-led',name:'EPA-led',desc:'Work backwards from the evidence and competence needed for EPA.',kind:'epa'},
 {id:'assessment-led',name:'Assessment-led',desc:'Structure around practical, theory, observation, witness and portfolio assessment.',kind:'assessment'},
 {id:'topic-led',name:'Topic / Theme-led',desc:'Group KSBs into occupational themes such as safety, tools, materials and communication.',kind:'topics'},
 {id:'progression-led',name:'Progression-led',desc:'Move from foundation through developing competence to EPA readiness.',kind:'progression'},
 {id:'spiral',name:'Spiral',desc:'Revisit important KSBs through increasingly advanced activities.',kind:'spiral'},
 {id:'custom',name:'Custom',desc:'Mix any of the rules and decide exactly how the course is built.',kind:'custom'}
];
const studioEsc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
const studioUid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`;
function masterDraft(){return{type:'KSB',title:'',ref:'',version:'',level:'',duration:'',duties:[],ksbs:[],units:[],structure:{template:'custom',rules:{}}}};
function parseStudioKsb(text){return String(text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).map(line=>{const m=line.match(/^([KSB])\s*([0-9]+)\s*[:\-–—]?\s*(.*)$/i);return m?{reference:m[1].toUpperCase()+m[2],ksb_type:m[1].toUpperCase(),description:m[3].trim()}:null}).filter(Boolean)}
function parseDuties(text){return String(text||'').split(/\n+/).map(x=>x.trim()).filter(Boolean).map((line,i)=>{const m=line.match(/^(?:D(?:uty)?\s*)?([0-9]+)\s*[:\-–—.]?\s*(.*)$/i);return{ id:studioUid(),reference:m?'D'+m[1]:'D'+(i+1),title:m?m[2].trim():line,description:''}})}
function studioStart(){
 state.draft=state.draft&&state.draft.id?state.draft:masterDraft(); renderStudio();
}
function studioCoverage(id){let n=0;(state.draft.units||[]).forEach(u=>(u.activities||[]).forEach(a=>n+=(a.ksb_ids||[]).filter(x=>x===id).length));return n}
function studioKsbPicker(selected=[],multi=true){return `<div class="studio-ksb-picker">${state.draft.ksbs.map(k=>`<label class="studio-ksb ${selected.includes(k.id)?'selected':''}"><input type="checkbox" data-ksb="${k.id}" ${selected.includes(k.id)?'checked':''}><span class="studio-ksb-ref ${k.ksb_type}">${studioEsc(k.reference)}</span><span class="studio-ksb-desc">${studioEsc(k.description)}</span><span class="studio-ksb-count">${studioCoverage(k.id)}×</span></label>`).join('')}</div>`}
function renderStudio(){
 const d=state.draft;if(!d)return;
 $('#builder').innerHTML=`<div class="studio-head"><div><span class="step-kicker">Naxos 3.0 course studio</span><h2>Build the master course</h2><p class="muted">Enter the course once. Naxos keeps the complete course separate from its evidence structure.</p></div><div class="studio-stat"><b>${d.ksbs.length}</b><span>KSBs</span><b>${d.duties.length}</b><span>Duties</span></div></div>
 <section class="studio-section"><div class="studio-section-title"><span>01</span><div><h3>Course information</h3><p>The master information stays available to every structure.</p></div></div><div class="type-grid"><button class="type-choice ${d.type==='KSB'?'selected':''}" data-type="KSB"><b>KSB Course</b><span>Standards-led course with KSB mapping.</span></button><button class="type-choice ${d.type==='NVQ'?'selected':''}" data-type="NVQ"><b>NVQ Course</b><span>Practical vocational course structure.</span></button></div><div class="form-grid"><label>Course title<input id="studioTitle" value="${studioEsc(d.title)}" placeholder="e.g. Bricklayer"></label><label>Standard / reference<input id="studioRef" value="${studioEsc(d.ref)}" placeholder="e.g. ST0095"></label><label>Version<input id="studioVersion" value="${studioEsc(d.version)}"></label><label>Level<input id="studioLevel" value="${studioEsc(d.level)}"></label><label>Duration<input id="studioDuration" value="${studioEsc(d.duration)}"></label></div></section>
 <section class="studio-section"><div class="studio-section-title"><span>02</span><div><h3>Duties</h3><p>Paste the occupational duties as well as the KSBs. Duties become available as a structure and mapping layer.</p></div></div><textarea id="studioDuties" rows="5" placeholder="One duty per line, for example:\nD1: Prepare for bricklaying operations\nD2: Construct brickwork\nD3: Complete brickwork operations">${studioEsc(d.duties.map(x=>`${x.reference}: ${x.title}`).join('\n'))}</textarea><div class="studio-chip-row">${d.duties.map(x=>`<span class="studio-chip"><b>${studioEsc(x.reference)}</b> ${studioEsc(x.title)}</span>`).join('')}</div></section>
 <section class="studio-section"><div class="studio-section-title"><span>03</span><div><h3>Complete KSB library</h3><p>Paste the full KSB list once. Descriptions are stored once and referenced by every generated structure.</p></div></div><textarea id="studioKsbPaste" rows="9" placeholder="K1: Full Knowledge description\nS1: Full Skill description\nB1: Full Behaviour description">${studioEsc(d.ksbs.map(x=>`${x.reference}: ${x.description}`).join('\n'))}</textarea><div class="studio-actions"><button class="secondary" id="studioImportKsb">Replace from pasted KSBs</button><button class="secondary" id="studioAppendKsb">Add pasted KSBs</button></div><div class="studio-summary">${['K','S','B'].map(t=>`<span><b>${d.ksbs.filter(x=>x.ksb_type===t).length}</b> ${t==='K'?'Knowledge':t==='S'?'Skills':'Behaviours'}</span>`).join('')}<span><b>${d.ksbs.length}</b> Total</span></div><div class="studio-library">${d.ksbs.slice(0,8).map(k=>`<div><b>${studioEsc(k.reference)}</b><span>${studioEsc(k.description)}</span></div>`).join('')}${d.ksbs.length>8?`<small>+ ${d.ksbs.length-8} more criteria</small>`:''}</div></section>
 <section class="studio-section studio-structure-section"><div class="studio-section-title"><span>04</span><div><h3>Generate a course structure</h3><p>Choose a starting structure. You can mix rules afterwards instead of rebuilding the master course.</p></div></div><div class="template-grid">${studioTemplates.map(t=>`<button class="template-card ${d.structure?.template===t.id?'selected':''}" data-template="${t.id}"><strong>${t.name}</strong><span>${t.desc}</span></button>`).join('')}</div><div class="mix-panel"><div><b>Mix &amp; match rules</b><span>Optional rules applied on top of the selected template.</span></div><div class="rule-grid"><label><span>Primary organisation</span><select id="rulePrimary">${['Duties','Skills','Knowledge','Units','Themes','Evidence','Custom'].map(x=>`<option ${d.structure?.rules?.primary===x?'selected':''}>${x}</option>`).join('')}</select></label><label><span>Evidence style</span><select id="ruleEvidence">${['Balanced','Holistic','Individual KSB','Photo-first','AI sorting','EPA-led','Custom'].map(x=>`<option ${d.structure?.rules?.evidence===x?'selected':''}>${x}</option>`).join('')}</select></label><label><span>KSB coverage</span><select id="ruleCoverage">${['Suggested','At least once','Repeated where useful','Multiple evidence points','Custom'].map(x=>`<option ${d.structure?.rules?.coverage===x?'selected':''}>${x}</option>`).join('')}</select></label><label><span>Learning progression</span><select id="ruleProgression">${['Standard','Progression-led','Spiral','EPA backwards'].map(x=>`<option ${d.structure?.rules?.progression===x?'selected':''}>${x}</option>`).join('')}</select></label></div></div><button class="studio-generate" id="studioGenerate">Generate structure</button></section>
 <section class="studio-section"><div class="studio-section-title"><span>05</span><div><h3>Generated structure</h3><p>Edit the generated units and activities after Naxos creates them.</p></div></div><div id="studioGenerated">${studioGeneratedHtml(d)}</div></section>
 <div class="designer-footer"><button class="secondary" id="studioCancel">Cancel</button><button class="next" id="studioSave">Save master course</button></div>`;
 $$('.type-choice').forEach(b=>b.onclick=()=>{d.type=b.dataset.type;renderStudio()});
 const fields={studioTitle:'title',studioRef:'ref',studioVersion:'version',studioLevel:'level',studioDuration:'duration'};Object.entries(fields).forEach(([id,key])=>$('#'+id).oninput=e=>d[key]=e.target.value);
 $('#studioDuties').onchange=e=>{d.duties=parseDuties(e.target.value);renderStudio()};
 $('#studioImportKsb').onclick=()=>{const rows=parseStudioKsb($('#studioKsbPaste').value);if(rows.length){d.ksbs=rows.map(x=>({...x,id:studioUid()}));renderStudio()}else alert('No KSBs recognised. Use K1:, S1: or B1: at the start of each line.')};
 $('#studioAppendKsb').onclick=()=>{parseStudioKsb($('#studioKsbPaste').value).forEach(x=>{if(!d.ksbs.some(k=>k.reference===x.reference))d.ksbs.push({...x,id:studioUid()})});renderStudio()};
 $$('#studioGenerated input,#studioGenerated select,#studioGenerated textarea').forEach(()=>{});
 $('#studioGenerate').onclick=()=>{d.structure.template=d.structure.template||'custom';d.structure.rules={primary:$('#rulePrimary').value,evidence:$('#ruleEvidence').value,coverage:$('#ruleCoverage').value,progression:$('#ruleProgression').value};generateStructure(d);renderStudio()};
 $$('.template-card').forEach(b=>b.onclick=()=>{d.structure.template=b.dataset.template;renderStudio()});
 $('#studioCancel').onclick=()=>show('home');$('#studioSave').onclick=studioSave;bindStudioGenerated();
}
function generateStructure(d){
 const t=studioTemplates.find(x=>x.id===d.structure.template)||studioTemplates[0];const oldUnits=d.units||[];let units=[];
 const makeActivity=(title,ksbIds=[],type='practical_evidence',dutyId=null)=>({id:studioUid(),title, type, photo_instruction:'',written_prompt:'',photo_required:type==='practical_evidence',written_required:true,ksb_ids:[...new Set(ksbIds)],duty_id:dutyId});
 if(t.kind==='duties'&&d.duties.length){units=d.duties.map((du,i)=>({id:studioUid(),title:du.reference+' — '+du.title,description:du.description||'',duty_id:du.id,ksb_ids:[],activities:[makeActivity('Evidence for '+du.reference, d.ksbs.filter((_,n)=>n%d.duties.length===i).map(k=>k.id),'practical_evidence',du.id)]}));}
 else if(t.kind==='skills'){const skills=d.ksbs.filter(k=>k.ksb_type==='S');units=[{id:studioUid(),title:'Skills programme',description:'Skill-led structure generated from the master course.',ksb_ids:[],activities:skills.map(s=>makeActivity(s.reference+' — '+s.description,[s.id,...d.ksbs.filter(k=>k.ksb_type!=='S'&&new RegExp('\\b'+s.reference.replace(/[.*+?^${}()|[\\]\\\\]/g,'\\\\$&')+'\\b','i').test(k.description)).slice(0,3).map(k=>k.id)]))}];}
 else if(t.kind==='knowledge'){const ks=d.ksbs.filter(k=>k.ksb_type==='K');units=[{id:studioUid(),title:'Knowledge programme',description:'Knowledge-led structure generated from the master course.',ksb_ids:[],activities:ks.map(k=>makeActivity(k.reference+' — '+k.description,[k.id],'knowledge_question'))}];}
 else if(t.kind==='individual'){units=[{id:studioUid(),title:'Individual KSB activities',description:'One activity per master KSB.',ksb_ids:[],activities:d.ksbs.map(k=>makeActivity(k.reference+' — '+k.description,[k.id],k.ksb_type==='K'?'knowledge_question':'practical_evidence'))}];}
 else if(t.kind==='holistic'){const chunks=Array.from({length:Math.max(1,Math.min(12,Math.ceil(d.ksbs.length/6)))},()=>[]);d.ksbs.forEach((k,i)=>chunks[i%chunks.length].push(k.id));units=[{id:studioUid(),title:'Holistic evidence programme',description:'Multi-KSB activities generated from the master course.',ksb_ids:[],activities:chunks.map((ids,i)=>makeActivity('Holistic evidence '+(i+1),ids))}];}
 else if(t.kind==='photo'||t.kind==='ai'){units=[{id:studioUid(),title:t.name+' evidence',description:t.desc,ksb_ids:[],activities:[makeActivity(t.kind==='photo'?'Workplace evidence collection':'AI evidence sorting',[],'practical_evidence')]}];}
 else if(t.id==='5x5x5'){units=Array.from({length:5},(_,i)=>({id:studioUid(),title:'Unit '+(i+1),description:'Generated 5 × 5 × 5 unit.',ksb_ids:[],activities:Array.from({length:5},(_,j)=>makeActivity('Activity '+(j+1),d.ksbs.filter((_,n)=>n%25===i*5+j).map(k=>k.id)))}));}
 else {const count=t.kind==='evidence'?Math.max(1,Math.ceil(d.ksbs.length/5)):Math.max(1,Math.min(12,Math.ceil(d.ksbs.length/8)));units=Array.from({length:count},(_,i)=>({id:studioUid(),title:t.name+' '+(i+1),description:t.desc,ksb_ids:[],activities:[makeActivity('Evidence activity '+(i+1),d.ksbs.filter((_,n)=>n%count===i).map(k=>k.id))]}));}
 d.units=units;
 if(d.structure.rules?.primary==='Duties'&&d.duties.length&&!units.some(u=>u.duty_id)){units.forEach((u,i)=>u.duty_id=d.duties[i%d.duties.length].id)}
 if(d.structure.rules?.evidence==='Individual KSB'&&t.kind!=='individual'){const all=d.ksbs.map(k=>makeActivity(k.reference+' — '+k.description,[k.id],k.ksb_type==='K'?'knowledge_question':'practical_evidence'));d.units=[{id:studioUid(),title:'Individual KSB evidence',description:'Generated by the selected evidence rule.',ksb_ids:[],activities:all}]}
}
function studioGeneratedHtml(d){if(!d.units?.length)return '<div class="studio-empty">Choose a structure and press <b>Generate structure</b>.</div>';return d.units.map((u,i)=>`<article class="studio-unit" data-unit="${u.id}"><div class="studio-unit-head"><span>${String(i+1).padStart(2,'0')}</span><div><input class="generated-unit-title" value="${studioEsc(u.title)}"><textarea class="generated-unit-desc" rows="2">${studioEsc(u.description||'')}</textarea></div><button class="remove-generated-unit">×</button></div><div class="studio-activity-list">${(u.activities||[]).map((a,j)=>`<div class="studio-activity" data-activity="${a.id}"><input class="generated-activity-title" value="${studioEsc(a.title)}"><select class="generated-activity-type"><option value="practical_evidence" ${a.type==='practical_evidence'?'selected':''}>Practical evidence</option><option value="knowledge_question" ${a.type==='knowledge_question'?'selected':''}>Knowledge</option><option value="witness_testimony" ${a.type==='witness_testimony'?'selected':''}>Witness testimony</option><option value="other" ${a.type==='other'?'selected':''}>Other</option></select><button class="remove-generated-activity">×</button><div class="generated-ksbs">${a.ksb_ids.map(id=>{const k=d.ksbs.find(x=>x.id===id);return k?`<span>${studioEsc(k.reference)}</span>`:''}).join('')}</div></div>`).join('')}</div><button class="add-generated-activity" data-unit="${u.id}">+ Add activity</button></article>`).join('')}
function bindStudioGenerated(){const d=state.draft;$$('.studio-unit').forEach(el=>{const u=d.units.find(x=>x.id===el.dataset.unit);el.querySelector('.generated-unit-title').oninput=e=>u.title=e.target.value;el.querySelector('.generated-unit-desc').oninput=e=>u.description=e.target.value;el.querySelector('.remove-generated-unit').onclick=()=>{d.units=d.units.filter(x=>x.id!==u.id);renderStudio()}});$$('.studio-activity').forEach(el=>{const a=d.units.flatMap(u=>u.activities).find(x=>x.id===el.dataset.activity);el.querySelector('.generated-activity-title').oninput=e=>a.title=e.target.value;el.querySelector('.generated-activity-type').onchange=e=>a.type=e.target.value;el.querySelector('.remove-generated-activity').onclick=()=>{const u=d.units.find(x=>x.activities.some(x=>x.id===a.id));u.activities=u.activities.filter(x=>x.id!==a.id);renderStudio()}});$$('.add-generated-activity').forEach(b=>b.onclick=()=>{const u=d.units.find(x=>x.id===b.dataset.unit);u.activities.push({id:studioUid(),title:'New activity',type:'practical_evidence',photo_instruction:'',written_prompt:'',photo_required:true,written_required:true,ksb_ids:[]});renderStudio()})}
function studioSave(){const d=state.draft;if(!d.title.trim()){alert('Enter a course title.');return}if(!d.ksbs.length){alert('Add the complete KSB library before saving.');return}const course={id:d.id||studioUid(),type:d.type,title:d.title.trim(),reference:d.ref.trim(),version:d.version.trim(),level:d.level.trim(),duration:d.duration.trim(),duties:d.duties.map(x=>({...x})),ksbs:d.ksbs.map(x=>({...x})),units:(d.units||[]).map(u=>({...u,ksb_ids:[...(u.ksb_ids||[])],activities:(u.activities||[]).map(a=>({...a,ksb_ids:[...(a.ksb_ids||[])]}))})),structure:d.structure,masterCourse:true};course.ksbCount=course.ksbs.length;course.packCount=course.units.length;course.activityCount=course.units.reduce((n,u)=>n+(u.activities||[]).length,0);if(d.id){const idx=state.courses.findIndex(x=>x.id===d.id);if(idx>=0)state.courses[idx]=course;else state.courses.push(course)}else state.courses.push(course);localStorage.setItem('naxos3_courses',JSON.stringify(state.courses));state.selected=course;state.draft=null;show('course')}
window.renderBuilder=renderStudio;window.startCreate=studioStart;window.saveCourse=studioSave;
})();
