(()=>{
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function course(){const title=document.querySelector('#courseHeading')?.textContent?.trim();return JSON.parse(localStorage.getItem('naxos3_courses')||'[]').find(c=>c.title===title)||null}
function courseMainTitle(c){const raw=String(c?.title||'').trim();return raw.replace(/\s*(v?\d+(?:\.\d+)?)\s*$/i,'').trim()||raw}
const FRONT=[['trade','Trade','Core trade skills and practical work'],['supporting','Supporting','Supporting skills and workplace practice'],['main','__COURSE__','Main occupational activities'],['knowledge','Knowledge','Knowledge requirements'],['behaviours','Behaviours','Professional behaviours and witness evidence']];
function openPreview(){const c=course();if(!c)return;let el=document.getElementById('eviaPreview');if(!el){el=document.createElement('div');el.id='eviaPreview';el.className='evia-preview-backdrop';document.body.appendChild(el)}
const sections=c.sections||[];const mainTitle=courseMainTitle(c);
el.innerHTML=`<div class="evia-preview-shell"><div class="evia-preview-top"><div><div class="eyebrow">Learner view</div><h2>Evia Preview</h2></div><button class="evia-preview-close" type="button" aria-label="Close preview">×</button></div><div class="evia-phone"><div class="evia-brand">EVIA</div><div class="evia-orb" aria-hidden="true"><div class="evia-face"><span class="evia-eye left"></span><span class="evia-eye right"></span></div></div><h1 class="evia-preview-title">${esc(mainTitle)}</h1><p class="evia-preview-sub">${esc(c.ref||'')} · ${esc(c.version||'')}</p><div class="evia-front-options">${FRONT.map(([type,title,desc])=>{const s=sections.find(x=>x.type===type);const label=title==='__COURSE__'?mainTitle:title;return `<button class="evia-front-option" type="button" data-section="${type}"><span class="evia-front-icon">${esc(label[0])}</span><span><strong>${esc(label)}</strong><small>${desc}</small></span><span class="evia-front-count">${s?.units?.length||0}</span><span class="chevron">›</span></button>`}).join('')}</div><div class="evia-section-detail" id="eviaSectionDetail"><p class="evia-preview-note">Select an option above to preview the learner's course area.</p></div></div></div>`;
el.classList.add('open');
const detail=el.querySelector('#eviaSectionDetail');
el.querySelectorAll('.evia-front-option').forEach(btn=>btn.onclick=()=>{const s=sections.find(x=>x.type===btn.dataset.section);if(!s)return;const label=btn.querySelector('strong')?.textContent||'';detail.innerHTML=`<div class="evia-detail-head"><button class="evia-detail-back" type="button">‹</button><div><div class="eyebrow">Evia</div><h3>${esc(label)}</h3></div></div>${(s.units||[]).map((u,i)=>`<article class="evia-pack"><h3>${i+1}. ${esc(u.title)}</h3><div class="evia-pack-meta">${(u.activities||[]).length} activities</div>${(u.activities||[]).map(a=>`<div class="evia-activity"><strong>${esc(a.title)}</strong>${a.photo_required?'<span class="evia-pill">Photo</span>':''}${a.written_required?'<span class="evia-pill">Written</span>':''}${a.reflection_required?'<span class="evia-pill">Reflection</span>':''}${a.photo_instruction?`<p>${esc(a.photo_instruction)}</p>`:''}${a.written_prompt?`<p>${esc(a.written_prompt)}</p>`:''}</div>`).join('')}</article>`).join('')}`;detail.querySelector('.evia-detail-back').onclick=()=>{detail.innerHTML='<p class="evia-preview-note">Select an option above to preview the learner\'s course area.</p>'}});
el.querySelector('.evia-preview-close').onclick=()=>el.classList.remove('open');el.onclick=e=>{if(e.target===el)el.classList.remove('open')}}
function addButton(){const header=document.querySelector('#courseView .page-header');if(!header||header.querySelector('.evia-preview-button'))return;const b=document.createElement('button');b.className='secondary evia-preview-button';b.type='button';b.textContent='Preview in Evia';b.onclick=openPreview;header.appendChild(b)}
new MutationObserver(addButton).observe(document.body,{childList:true,subtree:true});window.openEviaPreview=openPreview;
})();
