(()=>{
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
function course(){const title=document.querySelector('#courseHeading')?.textContent?.trim();return JSON.parse(localStorage.getItem('naxos3_courses')||'[]').find(c=>c.title===title)||null}
function flatten(c){return (c?.sections||[]).flatMap(s=>(s.units||[]).map(u=>({...u,section:s.title})));}
function openPreview(){const c=course();if(!c)return;let el=document.getElementById('eviaPreview');if(!el){el=document.createElement('div');el.id='eviaPreview';el.className='evia-preview-backdrop';document.body.appendChild(el)}const units=flatten(c);el.innerHTML=`<div class="evia-preview-shell"><div class="evia-preview-top"><div><div class="eyebrow">Learner view</div><h2>Evia Preview</h2></div><button class="evia-preview-close" type="button" aria-label="Close preview">×</button></div><div class="evia-phone"><div class="evia-brand">EVIA</div><div class="evia-orb" aria-hidden="true"><div class="evia-face"><span class="evia-eye left"></span><span class="evia-eye right"></span></div></div><h1 class="evia-preview-title">${esc(c.title)}</h1><p class="evia-preview-sub">${esc(c.ref||'')} · ${esc(c.version||'')}</p><div>${units.map((u,i)=>`<article class="evia-pack"><h3>${i+1}. ${esc(u.title)}</h3><div class="evia-pack-meta">${esc(u.section||'')} · ${(u.activities||[]).length} activities</div>${(u.activities||[]).map(a=>`<div class="evia-activity"><strong>${esc(a.title)}</strong>${a.photo_required?'<span class="evia-pill">Photo</span>':''}${a.written_required?'<span class="evia-pill">Written</span>':''}${a.reflection_required?'<span class="evia-pill">Reflection</span>':''}${a.photo_instruction?`<p>${esc(a.photo_instruction)}</p>`:''}${a.written_prompt?`<p>${esc(a.written_prompt)}</p>`:''}</div>`).join('')}</article>`).join('')}</div><p class="evia-preview-note">Preview only — this shows the learner-facing evidence flow without creating learner evidence.</p></div></div>`;el.classList.add('open');el.querySelector('.evia-preview-close').onclick=()=>el.classList.remove('open');el.onclick=e=>{if(e.target===el)el.classList.remove('open')}}
function addButton(){const header=document.querySelector('#courseView .page-header');if(!header||header.querySelector('.evia-preview-button'))return;const b=document.createElement('button');b.className='secondary evia-preview-button';b.type='button';b.textContent='Preview in Evia';b.onclick=openPreview;header.appendChild(b)}
const oldRender=window.renderCourse;if(typeof oldRender==='function'){window.renderCourse=function(){oldRender();addButton()}}
new MutationObserver(addButton).observe(document.body,{childList:true,subtree:true});
window.openEviaPreview=openPreview;
})();
