const KEY='naxos3_evidence_v2';
const COURSE={id:'ST0095-1.2',code:'ST0095',version:'1.2',title:'Bricklayer',packs:[
['Set out masonry','Solid/cavity set-out, openings, profiles, line, level and dimensions',['K10','K16','S5','S13','B3','K13','K21','S10','K9','S8','S4','K19'],['Drawing / dimensions','Wall and opening position','Profiles / gauge rod / square','Measurement and tolerance check','First course / finished set-out','Final line, level and dimensions']],
['Build cavity walling','Brick/block walling, returns, openings, bond and wall ties',['K22','S11','B3'],['Stretcher bond cavity wall','Return and opening','Wall ties before covering','Line, level and plumb checks','Lintel and opening detail','Finished cavity wall']],
['Install cavity details','Insulation, DPC, trays, weeps, fire stopping and closures',['K8','K22','S11','B3','K6','K5'],['Cavity before covering','Insulation continuity','DPC / cavity tray','Weep holes','Fire stopping / closure','Finished hidden-work check']],
['Form openings & lintels','Opening dimensions, lintels, bearing and feature courses',['K8','K10','K22','S5','S10','S11','K23','B3'],['Opening set-out','Lintel and bearing','Soldier / brick-on-edge course','Cavity closure','Final opening dimensions','Level and tolerance check']],
['Build solid walling','Solid walls, bonds, capping and quality checks',['K15','K16','S13','B3'],['Solid wall set-out','Bond pattern','Wall in progress','Capping detail','Line, level and plumb','Finished solid wall']],
['Build piers & decorative walling','Piers, projecting brickwork, contrasting and banding',['K18','K23','S11','B3'],['Pier / decorative set-out','Bond detail','Feature work in progress','Alignment and gauge','Finished feature','Final quality check']],
['Build raking or gable walling','Rake set-out, cutting, construction and finish',['K30','S22','K29','S15','B3'],['Rake line / template','Marked cuts','Cut units','Wall in progress','Finished rake','Final alignment / finish']],
['Mix mortar','Gauging, ratios, hand/mechanical/silo mixing',['K20','S14','K14','K8','B3'],['Materials','Ratio / gauging','Mixing process','Consistency check','Safe setup / controls','Finished mortar ready for use']],
['Cut bricks & blocks','Measure, mark, hand cut and power cut where appropriate',['K29','S15','K1','K14','S1','S8','B1','B3'],['Measurement','Marked cut','Tool selection','Safe control measures','Cutting process','Finished cut']],
['Apply joint finishes','Half-round, flush, weather-struck and recessed',['K17','S12','B3','K13'],['Joint before finishing','Tool selection','Finish in progress','Consistency check','Finished joints','Final quality check']],
['Repair brickwork','Identify defect, remove, replace and match',['K24','S16','K25','S17','B2','B3'],['Defect before work','Removal / preparation','Replacement','Joint and bond matching','Finished repair','Protection / final check']],
['Complete & protect masonry','Final checks, protection, waste and finished condition',['K7','S4','K24','K25','S17','B2','B3','K4','S3'],['Finished work','Quality check','Protection from weather / damage','Waste segregation','Clean final area','Final condition / sign-off']]
].map((p,i)=>({id:'pack-'+(i+1),number:i+1,title:p[0],summary:p[1],ksbs:p[2],photos:p[3]}))};
const state={screen:'home',pack:null,tab:'skills',data:load()};
function load(){try{return JSON.parse(localStorage.getItem(KEY)||'{}')}catch{return {}}}
function persist(){localStorage.setItem(KEY,JSON.stringify(state.data))}
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]))}
function packData(p){state.data[p.id]??={photos:{},descriptions:{},questions:['','',''],behaviour:'',saved:{}};return state.data[p.id]}
function go(screen){state.screen=screen;render();window.scrollTo(0,0)}
function home(){return `<main class="home"><div class="brand"><div class="naxos-face">N</div><h1>Naxos</h1><p>Evidence mapping source</p></div><button class="home-card" onclick="go('course')"><span class="icon">K</span><span><b>Bricklayer ST0095</b><small>Version 1.2 · 12 learner evidence packs</small></span><strong>›</strong></button><div class="home-note"><b>Naxosv2 source of truth</b><span>Skills, Knowledge, Behaviours and pack mappings are preserved. Naxos3.0 presents them as evidence workflows.</span></div></main>`}
function header(title,kicker=''){return `<header><button class="back" onclick="go(${state.screen==='pack'?'course':'home'})">‹</button><div>${kicker?`<small class="kicker">${esc(kicker)}</small>`:''}<h1>${esc(title)}</h1></div><button class="home-btn" onclick="go('home')">N</button></header>`}
function course(){return `<main class="page">${header('Bricklayer','ST0095 · VERSION 1.2')}<div class="course-rule"><b>Evidence rule</b><span>Skill = the photo. Knowledge = the photo description where it can genuinely be evidenced. Remaining Knowledge and Behaviours are combined into a maximum of 3 questions/reflections. Never ask for the same evidence twice.</span></div><div class="pack-list">${COURSE.packs.map(p=>{const d=packData(p),count=Object.keys(d.photos).length;return `<button class="pack" onclick="openPack('${p.id}')"><span class="pack-num">${String(p.number).padStart(2,'0')}</span><span class="pack-copy"><b>${esc(p.title)}</b><small>${esc(p.summary)}</small><em>${p.ksbs.join(' · ')}</em></span><span class="pack-progress">${count}/6</span></button>`}).join('')}</div></main>`}
function openPack(id){state.pack=COURSE.packs.find(p=>p.id===id);state.tab='skills';go('pack')}
function photoCard(p,i,d){const n=i+1;const has=!!d.photos[n];return `<article class="evidence-card"><div class="evidence-head"><span>PHOTO ${n}</span><b>${esc(p.photos[i])}</b><small>${has?'Captured':'Not captured'}</small></div><label class="photo-box ${has?'has-photo':''}"><input type="file" accept="image/*" capture="environment" onchange="photo(this,${n})"><span>${has?'Photo captured':'＋ Take photo'}</span></label><div class="pills">${p.ksbs.map(k=>`<span>${k}</span>`).join('')}<i>Auto-saved</i></div><label class="prompt">Description <small>Describe what you did, how you did it and why.</small><textarea data-pack="${p.id}" data-photo="${n}" oninput="description(this)" placeholder="Write what you did, how and why…">${esc(d.descriptions[n]||'')}</textarea></label></article>`}
function skills(p,d){return `<div class="notice">Each photo is the Skill evidence. The description records the Knowledge that can be evidenced from that same work. Do not repeat it elsewhere.</div>${p.photos.map((_,i)=>photoCard(p,i,d)).join('')}`}
function remaining(p,d){return `<div class="notice">Only use these questions for Knowledge that is <b>not</b> already evidenced by the Skill photos and descriptions, plus Behaviour reflections.</div><section class="question-card"><h2>Remaining Knowledge</h2><p>Maximum 3 questions for the unit.</p>${[1,2,3].map(n=>`<label>Question ${n}<textarea oninput="question(this,${n})" placeholder="Only ask what the photos and descriptions do not already cover…">${esc(d.questions[n-1]||'')}</textarea></label>`).join('')}</section>`}
function behaviours(p,d){return `<div class="notice">Behaviour evidence is reflection, not another copy of the practical task.</div><section class="question-card"><div class="ksb-title"><span>B</span><div><h2>Behaviour reflection</h2><p>Reflect on how you took ownership, worked safely and approached the work.</p></div></div><textarea oninput="behaviour(this)" placeholder="What did you do, how did you approach it, what did you learn and what would you improve?">${esc(d.behaviour)}</textarea></section>`}
function packView(){const p=state.pack,d=packData(p);return `<main class="page">${header(p.title,`PACK ${String(p.number).padStart(2,'0')}`)}<p class="summary">${esc(p.summary)}</p><div class="ksb-strip"><b>Mapped KSBs</b>${p.ksbs.map(k=>`<span>${k}</span>`).join('')}</div><nav class="tabs"><button class="${state.tab==='skills'?'active':''}" onclick="tab('skills')">Skills</button><button class="${state.tab==='knowledge'?'active':''}" onclick="tab('knowledge')">Knowledge</button><button class="${state.tab==='behaviours'?'active':''}" onclick="tab('behaviours')">Behaviours</button></nav><section class="tab-body">${state.tab==='skills'?skills(p,d):state.tab==='knowledge'?remaining(p,d):behaviours(p,d)}</section></main>`}
function photo(input,n){const p=state.pack,d=packData(p),file=input.files&&input.files[0];if(!file)return;const reader=new FileReader();reader.onload=()=>{d.photos[n]=reader.result;persist();render()};reader.readAsDataURL(file)}
function description(el){const d=packData(state.pack);d.descriptions[el.dataset.photo]=el.value;persist();saveFlash(el)}
function question(el,n){const d=packData(state.pack);d.questions[n-1]=el.value;persist();saveFlash(el)}
function behaviour(el){const d=packData(state.pack);d.behaviour=el.value;persist();saveFlash(el)}
function saveFlash(el){el.classList.add('saved');clearTimeout(el._t);el._t=setTimeout(()=>el.classList.remove('saved'),700)}
function tab(t){state.tab=t;render();window.scrollTo(0,0)}
function render(){document.querySelector('#root').innerHTML=state.screen==='home'?home():state.screen==='course'?course():packView()}
Object.assign(window,{go,openPack,photo,description,question,behaviour,tab});
document.addEventListener('DOMContentLoaded',render);